version: '2'
services:
    albanjarhipster-app:
        image: albanjarhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://albanjarhipster-mysql:3306/albanjarhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    albanjarhipster-mysql:
        extends:
            file: mysql.yml
            service: albanjarhipster-mysql
